'use strict';
window.LectureText=(()=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rtl=s=>/[\u0600-\u06ff]/.test(s.text),lines=s=>s.text.split('\n');
 function draw(c,s,w,h){const k=h/900;c.save();c.font=`${s.size*k}px Arial`;c.textBaseline='top';c.direction=rtl(s)?'rtl':'ltr';c.textAlign=rtl(s)?'right':'left';c.fillStyle=s.color;lines(s).forEach((t,i)=>c.fillText(t,s.points[0].x*w,s.points[0].y*h+i*s.size*k*1.3));c.restore();}
 function svg(s,w,h){return lines(s).map((t,i)=>`<text x="${s.points[0].x*w}" y="${s.points[0].y*h+(i*1.3+.85)*s.size*h/900}" font-family="Arial" font-size="${s.size*h/900}" fill="${s.color}" direction="${rtl(s)?'rtl':'ltr'}" text-anchor="start">${esc(t)}</text>`).join('');}
 function hit(s,p,w,h){if(s.kind!=='text')return false;const c=document.createElement('canvas').getContext('2d'),k=h/900;c.font=`${s.size*k}px Arial`;const width=Math.max(...lines(s).map(t=>c.measureText(t).width)),x=s.points[0].x*w-(rtl(s)?width:0),y=s.points[0].y*h;return p.x*w>=x-8&&p.x*w<=x+width+8&&p.y*h>=y-8&&p.y*h<=y+lines(s).length*s.size*k*1.3;}
 function edit(existing,done){const d=document.createElement('dialog');d.dir='rtl';d.style.cssText='width:min(480px,85vw);padding:24px;border:1px solid #ccc;border-radius:14px;z-index:10000';d.innerHTML='<form method="dialog"><h2>نص على الشريحة</h2><textarea aria-label="نص الملاحظة" maxlength="2000" rows="5" dir="auto" style="width:100%;box-sizing:border-box;font:18px Arial"></textarea><p><label>حجم النص <select><option>18</option><option>24</option><option>32</option><option>48</option><option>72</option></select></label></p><button value="save">حفظ النص</button> <button value="cancel">إلغاء</button> <button value="delete">حذف النص</button></form>';const ta=d.querySelector('textarea'),size=d.querySelector('select');ta.value=existing?.text||'';size.value=String(existing?.size||32);d.querySelector('[value=delete]').hidden=!existing;d.addEventListener('close',()=>{if(d.returnValue==='delete')done(null);if(d.returnValue==='save'&&ta.value.trim())done({kind:'text',text:ta.value,size:Number(size.value)});d.remove();});document.body.append(d);d.showModal();ta.focus();}
 return {draw,svg,hit,edit};
})();
