'use strict';
window.LectureText=(()=>{
 let editing=null,closeEditor=null;
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rtl=s=>/[\u0600-\u06ff]/.test(s.text),lines=s=>s.text.split('\n');
 function draw(c,s,w,h){if(s===editing)return;const k=h/900;c.save();c.font=`${s.weight||400} ${s.size*k}px Arial`;c.textBaseline='top';c.direction=rtl(s)?'rtl':'ltr';c.textAlign=rtl(s)?'right':'left';c.fillStyle=s.color;lines(s).forEach((t,i)=>c.fillText(t,s.points[0].x*w,s.points[0].y*h+i*s.size*k*1.3));c.restore();}
 function svg(s,w,h){return lines(s).map((t,i)=>`<text x="${s.points[0].x*w}" y="${s.points[0].y*h+(i*1.3+.85)*s.size*h/900}" font-family="Arial" font-weight="${s.weight||400}" font-size="${s.size*h/900}" fill="${s.color}" direction="${rtl(s)?'rtl':'ltr'}" text-anchor="start">${esc(t)}</text>`).join('');}
 function hit(s,p,w,h){if(s.kind!=='text')return false;const c=document.createElement('canvas').getContext('2d'),k=h/900;c.font=`${s.weight||400} ${s.size*k}px Arial`;const width=Math.max(...lines(s).map(t=>c.measureText(t).width)),x=s.points[0].x*w-(rtl(s)?width:0),y=s.points[0].y*h;return p.x*w>=x-8&&p.x*w<=x+width+8&&p.y*h>=y-8&&p.y*h<=y+lines(s).length*s.size*k*1.3;}
 function edit(existing,done,area='slide',canvas,point,redraw=()=>{}){
  closeEditor?.();if(!canvas)return;
  const root=document.createElement('div');root.className='inline-text-editor';root.setAttribute('role','group');root.setAttribute('aria-label','تحرير النص على الشريحة');
  root.style.cssText='position:fixed;z-index:10000;inset:0;pointer-events:none';
  root.innerHTML='<textarea aria-label="نص الملاحظة" maxlength="2000" rows="1" wrap="off" dir="auto" placeholder="اكتب هنا…" style="position:absolute;pointer-events:auto;box-sizing:border-box;padding:6px;margin:0;resize:none;border:2px solid #7c3aed;border-radius:5px;background:#ffffffed;outline:none;overflow:auto"></textarea><div role="toolbar" aria-label="تنسيق النص" dir="rtl" style="position:absolute;pointer-events:auto;display:flex;flex-wrap:wrap;gap:6px;align-items:center;padding:7px;background:white;border:1px solid #d9ccea;border-radius:8px;box-shadow:0 3px 12px #0002;font:13px Arial;width:max-content;max-width:calc(100vw - 20px)"><select aria-label="لون النص" name="color"><option value="#6d28d9">بنفسجي</option><option value="#dc2626">أحمر</option><option value="#2563eb">أزرق</option><option value="#172033">أسود</option></select><select aria-label="حجم النص" name="size"><option>18</option><option>24</option><option>32</option><option>48</option><option>72</option></select><select aria-label="سماكة النص" name="weight"><option value="400">عادي</option><option value="700">عريض</option><option value="900">عريض جدًا</option></select><button type="button" data-action="save">تم</button><button type="button" data-action="cancel">إلغاء</button><button type="button" data-action="delete">حذف</button></div>';
  const ta=root.querySelector('textarea'),bar=root.querySelector('[role=toolbar]'),field=n=>root.querySelector('[name="'+n+'"]'),anchor=existing?.points?.[0]||point;
  ta.value=existing?.text||'';field('size').value=String(existing?.size||32);field('color').value=existing?.color||'#6d28d9';field('weight').value=String(existing?.weight||400);root.querySelector('[data-action=delete]').hidden=!existing?.text;
  let closed=false;
  const value=()=>({kind:'text',text:ta.value,size:Number(field('size').value),color:field('color').value,weight:Number(field('weight').value)});
  const position=()=>{const r=canvas.getBoundingClientRect(),v=value(),font=v.size*r.height/900,isRtl=rtl(v),ctx=document.createElement('canvas').getContext('2d');ctx.font=`${v.weight} ${font}px Arial`;const width=Math.min(innerWidth-20,Math.max(160,...lines(v).map(t=>ctx.measureText(t).width+20))),height=Math.min(innerHeight*.6,Math.max(font*1.3+16,lines(v).length*font*1.3+16));const x=r.left+anchor.x*r.width,y=r.top+anchor.y*r.height,left=Math.max(8,Math.min(innerWidth-width-8,isRtl?x-width+8:x-8)),top=Math.max(8,Math.min(innerHeight-height-8,y-8));Object.assign(ta.style,{left:left+'px',top:top+'px',width:width+'px',height:height+'px',font:`${v.weight} ${font}px Arial`,lineHeight:'1.3',color:v.color,textAlign:isRtl?'right':'left'});const br=bar.getBoundingClientRect();bar.style.left=Math.max(8,Math.min(left,innerWidth-br.width-8))+'px';bar.style.top=(top+height+br.height+8<innerHeight?top+height+4:Math.max(8,top-br.height-4))+'px';};
  const finish=(action='save')=>{if(closed)return;closed=true;closeEditor=null;editing=null;document.removeEventListener('pointerdown',outside,true);window.removeEventListener('resize',position);window.removeEventListener('scroll',position,true);window.removeEventListener('pagehide',leave);root.remove();if(action==='delete'||(action==='save'&&!ta.value.trim()&&existing?.text))done(null,area);else if(action==='save'&&ta.value.trim())done(value(),area);redraw();};
  const outside=e=>{if(!root.contains(e.target))finish();},leave=()=>finish();
  root.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Escape'){e.preventDefault();finish('cancel');}else if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)){e.preventDefault();finish();}});
  root.addEventListener('focusout',()=>queueMicrotask(()=>{if(!closed&&!root.contains(document.activeElement))finish();}));
  for(const button of root.querySelectorAll('button'))button.onclick=()=>finish(button.dataset.action);
  ta.oninput=position;for(const select of root.querySelectorAll('select'))select.onchange=position;
  editing=existing;closeEditor=finish;document.body.append(root);position();redraw();ta.focus();ta.setSelectionRange(ta.value.length,ta.value.length);
  document.addEventListener('pointerdown',outside,true);window.addEventListener('resize',position);window.addEventListener('scroll',position,true);window.addEventListener('pagehide',leave);
 }
 // Preview dragging without mutating saved annotations. Commit only a valid drop.
 function drag(e,s,source,areas,commit,click){
  const id=e.pointerId,r=source.getBoundingClientRect(),start={x:e.clientX,y:e.clientY},offset={x:e.clientX-(r.left+s.points[0].x*r.width),y:e.clientY-(r.top+s.points[0].y*r.height)};let moved=false,ghost=null;
  const move=event=>{if(event.pointerId!==id)return;if(!moved&&Math.hypot(event.clientX-start.x,event.clientY-start.y)<5)return;event.preventDefault();moved=true;if(!ghost){ghost=document.createElement('div');ghost.textContent=s.text;Object.assign(ghost.style,{position:'fixed',pointerEvents:'none',zIndex:'10001',whiteSpace:'pre',font:`${s.weight||400} ${s.size*r.height/900}px Arial`,lineHeight:'1.3',color:s.color,direction:rtl(s)?'rtl':'ltr',transform:rtl(s)?'translateX(-100%)':'none',background:'#ffffffbb',outline:'1px dashed #7c3aed'});document.body.append(ghost);}ghost.style.left=(event.clientX-offset.x)+'px';ghost.style.top=(event.clientY-offset.y)+'px';};
  const stop=(event,cancel=false)=>{if(event.pointerId!==id)return;document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',cancelled,true);source.removeEventListener('lostpointercapture',cancelled);ghost?.remove();try{source.releasePointerCapture(id);}catch{}if(cancel)return;if(!moved){click();return;}for(const [area,c] of Object.entries(areas())){if(!c)continue;const box=c.getBoundingClientRect();if(!box.width||!box.height||event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)continue;commit(area,{x:Math.max(0,Math.min(1,(event.clientX-offset.x-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-offset.y-box.top)/box.height)),p:1});break;}};
  const up=e=>stop(e),cancelled=e=>stop(e,true);source.setPointerCapture(id);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',cancelled,true);source.addEventListener('lostpointercapture',cancelled);
 }
 return {draw,svg,hit,edit,drag};
})();
