'use strict';
window.LectureText=(()=>{
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const rtl=s=>/[\u0600-\u06ff]/.test(s.text),lines=s=>s.text.split('\n');
 function draw(c,s,w,h){const k=h/900;c.save();c.font=`${s.weight||400} ${s.size*k}px Arial`;c.textBaseline='top';c.direction=rtl(s)?'rtl':'ltr';c.textAlign=rtl(s)?'right':'left';c.fillStyle=s.color;lines(s).forEach((t,i)=>c.fillText(t,s.points[0].x*w,s.points[0].y*h+i*s.size*k*1.3));c.restore();}
 function svg(s,w,h){return lines(s).map((t,i)=>`<text x="${s.points[0].x*w}" y="${s.points[0].y*h+(i*1.3+.85)*s.size*h/900}" font-family="Arial" font-weight="${s.weight||400}" font-size="${s.size*h/900}" fill="${s.color}" direction="${rtl(s)?'rtl':'ltr'}" text-anchor="start">${esc(t)}</text>`).join('');}
 function hit(s,p,w,h){if(s.kind!=='text')return false;const c=document.createElement('canvas').getContext('2d'),k=h/900;c.font=`${s.weight||400} ${s.size*k}px Arial`;const width=Math.max(...lines(s).map(t=>c.measureText(t).width)),x=s.points[0].x*w-(rtl(s)?width:0),y=s.points[0].y*h;return p.x*w>=x-8&&p.x*w<=x+width+8&&p.y*h>=y-8&&p.y*h<=y+lines(s).length*s.size*k*1.3;}
 function edit(existing,done,area='slide'){
  const d=document.createElement('dialog');d.dir='rtl';d.style.cssText='width:min(480px,85vw);padding:24px;border:1px solid #ccc;border-radius:14px;z-index:10000';
  d.innerHTML='<form method="dialog"><h2>تحرير النص</h2><textarea aria-label="نص الملاحظة" maxlength="2000" rows="5" dir="auto" style="width:100%;box-sizing:border-box;font:18px Arial"></textarea><p><label>حجم النص <select name="size"><option>18</option><option>24</option><option>32</option><option>48</option><option>72</option></select></label></p><p><label>لون النص <select name="color"><option value="#6d28d9">بنفسجي</option><option value="#dc2626">أحمر</option><option value="#2563eb">أزرق</option><option value="#172033">أسود</option></select></label></p><p><label>سماكة النص <select name="weight"><option value="400">عادي</option><option value="700">عريض</option><option value="900">عريض جدًا</option></select></label></p><p><label>مكان النص <select name="area"><option value="slide">داخل الشريحة</option><option value="note">المساحة الجانبية</option></select></label></p><p>اسحب النص بأداة النص لنقله، أو انقر عليه لتعديله.</p><button value="save">حفظ النص</button> <button value="cancel">إلغاء</button> <button value="delete">حذف النص</button></form>';
  const ta=d.querySelector('textarea'),field=n=>d.querySelector('[name="'+n+'"]');ta.value=existing?.text||'';field('size').value=String(existing?.size||32);field('color').value=existing?.color||'#6d28d9';field('weight').value=String(existing?.weight||400);field('area').value=area;d.querySelector('[value=delete]').hidden=!existing?.text;
  const preview=()=>{ta.style.color=field('color').value;ta.style.fontWeight=field('weight').value;};field('color').onchange=preview;field('weight').onchange=preview;preview();
  d.addEventListener('close',()=>{if(d.returnValue==='delete')done(null,area);if(d.returnValue==='save'&&ta.value.trim())done({kind:'text',text:ta.value,size:Number(field('size').value),color:field('color').value,weight:Number(field('weight').value)},field('area').value);d.remove();});document.body.append(d);d.showModal();ta.focus();
 }
 // Preview dragging without mutating saved annotations. Commit only a valid drop.
 function drag(e,s,source,areas,commit,click){
  const id=e.pointerId,r=source.getBoundingClientRect(),start={x:e.clientX,y:e.clientY},offset={x:e.clientX-(r.left+s.points[0].x*r.width),y:e.clientY-(r.top+s.points[0].y*r.height)};let moved=false,ghost=null;
  const move=event=>{if(event.pointerId!==id)return;if(!moved&&Math.hypot(event.clientX-start.x,event.clientY-start.y)<5)return;event.preventDefault();moved=true;if(!ghost){ghost=document.createElement('div');ghost.textContent=s.text;Object.assign(ghost.style,{position:'fixed',pointerEvents:'none',zIndex:'10001',whiteSpace:'pre',font:`${s.weight||400} ${s.size*r.height/900}px Arial`,lineHeight:'1.3',color:s.color,direction:rtl(s)?'rtl':'ltr',transform:rtl(s)?'translateX(-100%)':'none',background:'#ffffffbb',outline:'1px dashed #7c3aed'});document.body.append(ghost);}ghost.style.left=(event.clientX-offset.x)+'px';ghost.style.top=(event.clientY-offset.y)+'px';};
  const stop=(event,cancel=false)=>{if(event.pointerId!==id)return;document.removeEventListener('pointermove',move,true);document.removeEventListener('pointerup',up,true);document.removeEventListener('pointercancel',cancelled,true);source.removeEventListener('lostpointercapture',cancelled);ghost?.remove();try{source.releasePointerCapture(id);}catch{}if(cancel)return;if(!moved){click();return;}for(const [area,c] of Object.entries(areas())){if(!c)continue;const box=c.getBoundingClientRect();if(!box.width||!box.height||event.clientX<box.left||event.clientX>box.right||event.clientY<box.top||event.clientY>box.bottom)continue;commit(area,{x:Math.max(0,Math.min(1,(event.clientX-offset.x-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-offset.y-box.top)/box.height)),p:1});break;}};
  const up=e=>stop(e),cancelled=e=>stop(e,true);source.setPointerCapture(id);document.addEventListener('pointermove',move,true);document.addEventListener('pointerup',up,true);document.addEventListener('pointercancel',cancelled,true);source.addEventListener('lostpointercapture',cancelled);
 }
 return {draw,svg,hit,edit,drag};
})();
