'use strict';
(()=>{
 const $=id=>document.getElementById(id),w=window.LectureWorkspace,all=window.LECTURE_SLIDES;
 let drawingLink=null;
 let library={revision:0,courses:[{id:'dsa',name:'هياكل البيانات والخوارزميات باستخدام Python'}],hidden:[],links:{}},prefs={revision:0,terms:[]},chapter='all',coverMode=false;
 const clone=x=>JSON.parse(JSON.stringify(x)),admin=()=>w.account()?.role==='admin';

 let draft=null,draftOwner=null;
 const empty=()=>({slide:[],note:[]});
 const draftKey=()=> 'lecture-shared-draft:'+w.account()?.id;
 function rawEditor(){if(!admin()||!w.isRaw())return null;if(draftOwner!==w.account().id){draft=null;draftOwner=w.account().id;}if(!draft){try{draft=JSON.parse(localStorage.getItem(draftKey()));}catch{}if(!draft||typeof draft.annotations!=='object')draft={revision:library.revision,annotations:clone(library.annotations||{}),base:JSON.stringify(library.annotations||{})};}return draft;}
 function saveDraft(){if(!draft||!admin())return;const changed=JSON.stringify(draft.annotations)!==draft.base;try{if(changed)localStorage.setItem(draftKey(),JSON.stringify(draft));else localStorage.removeItem(draftKey());}catch{w.toast('تعذّر حفظ المسودة محليًا. احفظ الملاحظات للجميع قبل إغلاق الصفحة.');}if(w.isRaw())$('saveStatus').textContent=changed?'مسودة مشتركة · اضغط حفظ الملاحظات للجميع':'الملاحظات المشتركة محفوظة';}
 function combined(id,session){if(!session)return (rawEditor()?.annotations||library.annotations||{})[id]||empty();const shared=session.sharedHidden?.notes?.includes(id)?empty():library.annotations?.[id]||empty(),own=session.annotations?.[id]||empty();return {slide:[...shared.slide,...own.slide],note:[...shared.note,...own.note]};}
 function visibleLinks(id){return !w.isRaw()&&w.sharedHidden().links.includes(id)?[]:library.links[id]||[];}
 $('saveSharedBtn').onclick=()=>safely(async()=>{w.current();const d=rawEditor();if(!d)return;const next={...clone(library),revision:d.revision,annotations:clone(d.annotations)};await persist('library',next);draft=null;localStorage.removeItem(draftKey());w.resetHistory();w.refresh();w.toast('حُفظت الملاحظات المشتركة لجميع المدرسين والشعب.');});
 $('sharedContentBtn').onclick=()=>{const body=dialog('المحتوى المشترك · '+w.context().slide.title);if(w.isRaw()){body.append(el('p',admin()?'اكتب على الشرائح الخام بالقلم، ثم اضغط «حفظ الملاحظات للجميع». الروابط تُحفظ مباشرة من «روابط الشريحة»، والأغطية المشتركة تُحفظ مباشرة عند رسمها. كشف الغطاء هنا معاينة فقط.':'ملاحظات الشرائح الخام وروابطها مشتركة من مالك المحتوى. يمكنك إخفاؤها في شعبتك.'));if(admin())body.append(button('إلغاء المسودة المحلية وإعادة النسخة المحفوظة',()=>{draft=null;localStorage.removeItem(draftKey());w.resetHistory();$('libraryDialog').close();w.refresh();}));return;}body.append(el('p','هذه الخيارات للشريحة الحالية في هذه الشعبة فقط. ملاحظاتك الخاصة تبقى كما هي. انشر الملاحظات لتحديث رابط الطلبة.'));const id=w.context().slide.id;for(const [kind,label] of [['notes','إظهار الملاحظات المشتركة'],['links','إظهار الروابط المشتركة'],['covers','إظهار الأغطية المشتركة']]){const row=el('label',label),input=el('input');input.type='checkbox';input.checked=!w.sharedHidden()[kind].includes(id);input.onchange=()=>{const value=w.sharedHidden();value[kind]=input.checked?value[kind].filter(x=>x!==id):[...new Set([...value[kind],id])];w.setSharedHidden(value);};row.prepend(input);body.append(row);}};
 function el(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
 function button(text,action){const b=el('button',text);b.type='button';b.onclick=action;return b;}
 function dialog(title){$('libraryDialogTitle').textContent=title;$('libraryDialogBody').replaceChildren();$('libraryDialog').showModal();return $('libraryDialogBody');}
 $('closeLibraryDialog').onclick=()=>$('libraryDialog').close();
 const term=()=>prefs.terms.find(t=>t.courseId===w.context().courseId&&t.name===w.context().term);
 function allTerms(){const list=clone(prefs.terms);for(const s of w.context().sessions)if(!list.some(t=>t.courseId===(s.courseId||'dsa')&&t.name===s.term))list.push({courseId:s.courseId||'dsa',name:s.term,active:w.context().sessions.some(x=>(x.courseId||'dsa')===(s.courseId||'dsa')&&x.term===s.term&&!x.archived),hidden:[]});return list;}
 async function persist(type,value){const result=await window.saveLectureSetting(type,value);if(type==='library'){if(draft&&draft.revision===library.revision)draft.revision=result.data.revision;library=result.data;saveDraft();}else prefs=result.data;w.refresh();renderHome();return result.data;}
 async function safely(action){try{await action();}catch(e){w.toast(e.message||'تعذّر حفظ التغيير.');}}
 function open(courseId,termName){if(!all.some(s=>s.courseId===courseId)){w.toast('المادة جاهزة؛ لم تضف شرائحها بعد.');return;}document.body.classList.remove('home-view');$('homePage').hidden=true;w.openCourse(courseId,termName);}
 function renderHome(){const courses=$('courseCards');courses.replaceChildren();for(const c of library.courses){const card=el('article',null,'course-card');card.append(el('h3',c.name),el('p',`${all.filter(s=>s.courseId===c.id).length} شريحة · ${allTerms().filter(t=>t.courseId===c.id&&t.active).length} فصل دراسي فعال`),button('فتح المادة',()=>open(c.id,allTerms().find(t=>t.courseId===c.id&&t.active)?.name)));courses.append(card);}
 $('addCourseBtn').hidden=!admin();$('termCards').replaceChildren();$('inactiveTerms').replaceChildren();for(const t of allTerms()){const card=el('article',null,'term-card');card.append(el('h3',t.name),el('p',library.courses.find(c=>c.id===t.courseId)?.name||t.courseId));if(t.active)card.append(button('فتح الشعب',()=>open(t.courseId,t.name)));card.append(button(t.active?'إنهاء الفصل الدراسي':'إعادة تفعيل الفصل',()=>safely(async()=>{if(t.active&&!confirm('سيختفي الفصل من السجل الفعال ويتوقف عرض روابط شعبه للطلبة. يمكنك إعادة تفعيله لاحقًا.'))return;const next={...clone(prefs),terms:allTerms()};next.terms.find(x=>x.courseId===t.courseId&&x.name===t.name).active=!t.active;await persist('preferences',next);})));$(t.active?'termCards':'inactiveTerms').append(card);}}
 function home(){document.body.classList.add('home-view');$('homePage').hidden=false;renderHome();}
 $('homeBtn').onclick=home;$('directPrintBtn').onclick=()=>w.print();
 $('addCourseBtn').onclick=()=>{const body=dialog('مادة جديدة');const input=el('input');input.placeholder='اسم المادة';input.maxLength=100;input.setAttribute('aria-label','اسم المادة');body.append(input,button('حفظ المادة',()=>safely(async()=>{if(!input.value.trim())throw Error('أدخل اسم المادة.');const next=clone(library);next.courses.push({id:'course-'+crypto.randomUUID(),name:input.value.trim()});await persist('library',next);$('libraryDialog').close();})));};
 $('addTermBtn').onclick=()=>{const body=dialog('فصل دراسي جديد');const select=el('select');select.setAttribute('aria-label','المادة');for(const c of library.courses)select.add(new Option(c.name,c.id));const input=el('input');input.placeholder='مثال: ربيع 2027';input.maxLength=70;input.setAttribute('aria-label','اسم الفصل الدراسي');body.append(select,input,button('إنشاء الفصل',()=>safely(async()=>{const name=input.value.trim();if(!name)throw Error('أدخل اسم الفصل الدراسي.');const terms=allTerms();if(terms.some(t=>t.courseId===select.value&&t.name===name))throw Error('هذا الفصل موجود لهذه المادة.');terms.push({courseId:select.value,name,active:true,hidden:[]});await persist('preferences',{...clone(prefs),terms});$('libraryDialog').close();})));};
 $('chapterSelect').onchange=e=>{chapter=e.target.value;w.refresh();};
 function visibility(){if(w.isRaw()&&!admin()){w.toast('الشرائح الخام للعرض فقط. افتح شعبتك لإدارة ظهور الشرائح.');return;}const body=dialog('ظهور الشرائح');body.append(el('p','إخفاء الفصل الدراسي يشمل جميع شعبك فيه. الإخفاء العام يعلو على الاختيار المحلي لدى جميع المدرسين.'));for(const s of all.filter(s=>s.courseId===w.context().courseId)){const row=el('div',null,'visibility-row');row.append(el('span',`الفصل ${s.chapter} · ${s.title}`));const localHidden=term()?.hidden.includes(s.id);const localButton=button(localHidden?'إظهار في الفصل الدراسي':'إخفاء في الفصل الدراسي',()=>safely(async()=>{const next={...clone(prefs),terms:allTerms()};let target=next.terms.find(t=>t.courseId===w.context().courseId&&t.name===w.context().term);if(!target){target={courseId:w.context().courseId,name:w.context().term,active:true,hidden:[]};next.terms.push(target);}target.hidden=target.hidden.includes(s.id)?target.hidden.filter(id=>id!==s.id):[...target.hidden,s.id];await persist('preferences',next);$('libraryDialog').close();visibility();}));localButton.disabled=!w.context().term;localButton.title=w.context().term?'':'أنشئ فصلًا دراسيًا أو فعّل فصلًا سابقًا أولًا';if(!w.isRaw())row.append(localButton);if(admin())row.append(button(library.hidden.includes(s.id)?'إظهار للجميع':'إخفاء عن الجميع',()=>safely(async()=>{const next=clone(library);next.hidden=next.hidden.includes(s.id)?next.hidden.filter(id=>id!==s.id):[...next.hidden,s.id];await persist('library',next);$('libraryDialog').close();visibility();})));else if(library.hidden.includes(s.id))row.append(el('small','مخفية من مالك المحتوى'));body.append(row);}}
 $('visibilityBtn').onclick=visibility;
 function linksDialog(notice='',selected=-1){
  const slide=w.context().slide,body=dialog('إدارة روابط: '+slide.title),list=library.links[slide.id]||[];
  body.append(el('p','يمكن إضافة عدة روابط ومناطق مستقلة. اختر رابطًا لتعديل اسمه وعنوانه ومنطقته.'));
  const status=el('p',notice,'link-status');status.setAttribute('role','status');body.append(status);
  const selector=el('select');selector.setAttribute('aria-label','اختيار الرابط');selector.add(new Option('＋ رابط جديد','-1'));list.forEach((l,i)=>selector.add(new Option(`${i+1}. ${l.label}${l.rect?' · منطقة محددة':''}`,String(i))));selector.value=String(selected);selector.onchange=()=>linksDialog('',Number(selector.value));body.append(selector);
  const item=list[selected],form=el('form'),label=el('input'),url=el('input');label.maxLength=160;url.maxLength=2000;url.dir='ltr';url.inputMode='url';label.value=item?.label||'';url.value=item?.url||'';url.placeholder='https://example.com';
  const lf=el('label','اسم الرابط'),uf=el('label','عنوان الموقع أو الملف');lf.append(label);uf.append(url);form.append(lf,uf);
  if(!admin()){label.readOnly=url.readOnly=true;body.append(form,el('p','يدير مالك المحتوى الروابط المشتركة.'));return;}
  const submit=el('button',item?'حفظ تعديلات الرابط':'إضافة الرابط');submit.type='submit';form.append(submit);body.append(form);
  if(item){body.append(button(item.rect?'إعادة تحديد منطقة هذا الرابط':'تحديد منطقة هذا الرابط',()=>startLinkDrawing(slide.id,selected,item)));if(item.rect)body.append(button('إزالة المنطقة فقط',()=>safely(async()=>{const next=clone(library);delete next.links[slide.id][selected].rect;await persist('library',next);linksDialog('أُزيلت المنطقة وبقي الرابط.',selected);})));body.append(button('حذف هذا الرابط',()=>safely(async()=>{const next=clone(library);next.links[slide.id].splice(selected,1);await persist('library',next);linksDialog('حُذف الرابط.');})));}
  form.onsubmit=async e=>{e.preventDefault();if(submit.disabled)return;try{if(!label.value.trim())throw Error('اكتب اسم الرابط.');let address=url.value.trim();if(!address)throw Error('أدخل عنوان الموقع أو الملف.');if(!/^[a-z][a-z0-9+.-]*:/i.test(address))address='https://'+address;let parsed;try{parsed=new URL(address);}catch{throw Error('الرابط غير صالح.');}if(!['http:','https:'].includes(parsed.protocol)||parsed.username||parsed.password||(!parsed.hostname.includes('.')&&parsed.hostname!=='localhost'))throw Error('استخدم رابط موقع كاملًا يبدأ بـ https:// أو http://.');if(!item&&list.length>=20)throw Error('الحد الأقصى 20 رابطًا للشريحة.');submit.disabled=true;const next=clone(library),value={...(item||{}),label:label.value.trim(),url:parsed.href};next.links[slide.id] ||= [];if(item)next.links[slide.id][selected]=value;else next.links[slide.id].push(value);await persist('library',next);linksDialog('تم حفظ الرابط. يمكنك تحديد منطقته أو اختيار رابط آخر.',item?selected:next.links[slide.id].length-1);}catch(err){status.textContent=err.message;status.classList.add('error');}finally{submit.disabled=false;}};
 }

 function cancelLinkDrawing(){drawingLink=null;$('linkDrawLayer').hidden=true;$('linkDrawLayer').replaceChildren();$('linkDrawHelp').hidden=true;}
 function startLinkDrawing(slideId,index,link){coverMode=false;renderCovers();drawingLink={slideId,index,url:link.url};$('libraryDialog').close();$('linkDrawLayer').hidden=false;$('linkDrawHelp').hidden=false;}
 $('cancelLinkDraw').onclick=cancelLinkDrawing;
 const linkLayer=$('linkDrawLayer');let linkStart=null;
 const linkPoint=e=>{const r=linkLayer.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};
 linkLayer.onpointerdown=e=>{if(!drawingLink||e.button!==0)return;e.preventDefault();linkLayer.setPointerCapture(e.pointerId);linkStart={...linkPoint(e),id:e.pointerId};};
 linkLayer.onpointermove=e=>{if(!linkStart||e.pointerId!==linkStart.id)return;const end=linkPoint(e);let preview=linkLayer.firstElementChild;if(!preview){preview=el('div',null,'link-draw-preview');linkLayer.append(preview);}Object.assign(preview.style,{left:Math.min(linkStart.x,end.x)*100+'%',top:Math.min(linkStart.y,end.y)*100+'%',width:Math.abs(end.x-linkStart.x)*100+'%',height:Math.abs(end.y-linkStart.y)*100+'%'});};
 linkLayer.onpointerup=async e=>{if(!linkStart||e.pointerId!==linkStart.id||!drawingLink)return;const start=linkStart,end=linkPoint(e),target=drawingLink;linkStart=null;const rect={x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(start.x-end.x),h:Math.abs(start.y-end.y)};cancelLinkDrawing();if(rect.w<.01||rect.h<.01){w.toast('حدد مساحة أكبر قليلًا للرابط.');return;}try{const next=clone(library);if(next.links[target.slideId]?.[target.index]?.url!==target.url)throw Error('تغير الرابط أثناء التحديد. افتح الروابط وحاول مجددًا.');next.links[target.slideId][target.index].rect=rect;await persist('library',next);w.toast('حُفظت منطقة الرابط. مرر المؤشر عليها أو اضغط لفتحها.');}catch(e){w.toast(e.message);}};
 linkLayer.onpointercancel=()=>{linkStart=null;cancelLinkDrawing();};
 $('showLinks').onchange=e=>document.body.classList.toggle('links-hidden',!e.target.checked);
 $('linksBtn').onclick=()=>linksDialog();
 const rawCoverPreview=new Set();
 function combinedCovers(id,session){const shared=session?.sharedHidden?.covers?.includes(id)?[]:library.covers?.[id]||[];return [...shared.map(c=>({...c,_shared:true,revealed:session?!!session.revealedSharedCovers?.includes(c.id):rawCoverPreview.has(c.id)})),...(session?.covers?.[id]||[])];}
 function shownCovers(){return combinedCovers(w.context().slide.id,w.current());}
 async function saveCentral(covers){const next=clone(library);next.covers ||= {};next.covers[w.context().slide.id]=covers.map(({_shared,...c})=>c);await persist('library',next);w.toast('حُفظت الأغطية المشتركة للجميع.');}
 function revealCover(c,i){if(c._shared){if(w.isRaw()){rawCoverPreview.add(c.id);renderCovers();return;}w.setRevealedSharedCovers([...new Set([...w.revealedSharedCovers(),c.id])]);}else{const covers=w.covers();const ownIndex=i-shownCovers().filter(x=>x._shared).length;covers[ownIndex].revealed=true;w.setCovers(covers);}renderCovers();}
 function renderCovers(){const layer=$('coverLayer');layer.replaceChildren();for(const [i,c] of shownCovers().entries()){if(c.revealed)continue;const central=library.covers?.[w.context().slide.id]||[];const label=c._shared?`الغطاء المشترك ${central.findIndex(x=>x.id===c.id)+1}`:`غطاء الشعبة ${i-shownCovers().filter(x=>x._shared).length+1}`;const b=button(label,()=>revealCover(c,i));b.title=label+' · اضغط لكشف الإجابة';b.setAttribute('aria-label',label+' · كشف الإجابة');b.className='answer-cover';Object.assign(b.style,{left:c.x*100+'%',top:c.y*100+'%',width:c.w*100+'%',height:c.h*100+'%'});layer.append(b);}layer.classList.toggle('drawing-cover',coverMode);$('coverBtn').classList.toggle('selected',coverMode);}
 $('coverBtn').onclick=()=>{if(w.isRaw()&&!admin())return;cancelLinkDrawing();coverMode=!coverMode;renderCovers();w.toast(coverMode?'اسحب فوق الجزء المراد تغطيته.':'انتهى وضع رسم الغطاء.');};
 $('resetCoversBtn').onclick=()=>safely(async()=>{if(w.isRaw()){rawCoverPreview.clear();}else{const ids=new Set((library.covers?.[w.context().slide.id]||[]).map(c=>c.id));w.setRevealedSharedCovers(w.revealedSharedCovers().filter(id=>!ids.has(id)));w.setCovers(w.covers().map(c=>({...c,revealed:false})));}renderCovers();});
 $('manageCoversBtn').onclick=()=>{const body=dialog('أغطية الشريحة');const central=library.covers?.[w.context().slide.id]||[];central.forEach((c,i)=>{if(w.isRaw()){if(admin())body.append(button(`حذف الغطاء المشترك ${i+1}`,()=>safely(async()=>{await saveCentral(central.filter(x=>x.id!==c.id));$('libraryDialog').close();})));}else body.append(button(`${w.revealedSharedCovers().includes(c.id)?'إعادة':'كشف'} الغطاء المشترك ${i+1} في هذه الشعبة`,()=>{const ids=w.revealedSharedCovers();w.setRevealedSharedCovers(ids.includes(c.id)?ids.filter(id=>id!==c.id):[...ids,c.id]);renderCovers();$('libraryDialog').close();}));});w.covers().forEach((c,i)=>body.append(button(`حذف غطاء الشعبة ${i+1}`,()=>{w.setCovers(w.covers().filter((_,j)=>j!==i));renderCovers();$('libraryDialog').close();})));if(!central.length&&!w.covers().length)body.append(el('p','لم تضف أغطية لهذه الشريحة.'));};
 let drag=null;const layer=$('coverLayer');const point=e=>{const r=layer.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};};
 layer.onpointerdown=e=>{if(!coverMode||(w.isRaw()&&!admin())||e.button!==0)return;e.preventDefault();layer.setPointerCapture(e.pointerId);drag={...point(e),id:e.pointerId};};
 layer.onpointermove=e=>{if(!drag||e.pointerId!==drag.id)return;let preview=layer.querySelector('.cover-preview');if(!preview){preview=el('div',null,'answer-cover cover-preview');layer.append(preview);}const p=point(e);Object.assign(preview.style,{left:Math.min(p.x,drag.x)*100+'%',top:Math.min(p.y,drag.y)*100+'%',width:Math.abs(p.x-drag.x)*100+'%',height:Math.abs(p.y-drag.y)*100+'%'});};
 layer.onpointerup=e=>{if(!drag||e.pointerId!==drag.id)return;const p=point(e),c={x:Math.min(p.x,drag.x),y:Math.min(p.y,drag.y),w:Math.abs(p.x-drag.x),h:Math.abs(p.y-drag.y),revealed:false};drag=null;coverMode=false;if(c.w>.01&&c.h>.01){if(w.isRaw())safely(()=>saveCentral([...(library.covers?.[w.context().slide.id]||[]),{...c,id:crypto.randomUUID()}]));else w.setCovers([...w.covers(),c]);}renderCovers();};layer.onpointercancel=()=>{drag=null;renderCovers();};
 window.LectureLibrary={activate:(lib,preferences)=>{library=lib;prefs=preferences;draft=null;w.refresh();home();},termInactive:(courseId,name)=>allTerms().some(t=>t.courseId===courseId&&t.name===name&&!t.active),terms:id=>allTerms().filter(t=>t.courseId===id&&t.active).map(t=>t.name),selectSlides:(id,name)=>{const hidden=new Set([...library.hidden,...(w.isRaw()?[]:prefs.terms.find(t=>t.courseId===id&&t.name===name)?.hidden||[])]);return all.filter(s=>s.courseId===id&&!hidden.has(s.id)&&(chapter==='all'||s.chapter===chapter));},isHidden:id=>library.hidden.includes(id)||(!w.isRaw()&&!!term()?.hidden.includes(id)),rawEditor,saveDraft,combined,combinedCovers,links:visibleLinks,showLinks:()=>$('showLinks').checked,onSlide:slide=>{document.body.classList.toggle('raw-readonly',w.isRaw()&&!admin());$('linksBtn').hidden=!admin();$('sharedContentBtn').hidden=w.isRaw()&&!admin();$('saveSharedBtn').hidden=!admin()||!w.isRaw();$('sharedContentBtn').disabled=slide.id==='empty';if(w.isRaw()&&admin()){$('toolHint').textContent='ملاحظات مشتركة · احفظها للجميع بعد الكتابة';saveDraft();}cancelLinkDrawing();coverMode=false;renderCovers();window.LectureLinks.render(document.querySelector('.workspace'),$('slideSurface'),$('slideLinks'),visibleLinks(slide.id),w.inkPointer);$('linksBtn').disabled=slide.id==='empty';$('coverBtn').disabled=(w.isRaw()&&!admin())||slide.id==='empty';}};
 // Shared visibility applies on the next refresh, including another teacher's open editor.
 setInterval(async()=>{if(!w.account())return;try{const response=await fetch(window.LECTURE_PUBLISHING.apiBase+'/api/library',{cache:'no-store'});if(!response.ok)return;const next=await response.json();if(next.revision!==library.revision){library=next;w.refresh();renderHome();}}catch{}},60000);
})();
