'use strict';
(()=>{
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 function areas(links){return links.map((l,i)=>l.rect?`<a class="link-hotspot" data-link-index="${i}" href="${escape(l.url)}" target="_blank" rel="noopener noreferrer" aria-label="${escape(l.label)}" title="${escape(l.label)}" style="left:${l.rect.x*100}%;top:${l.rect.y*100}%;width:${l.rect.w*100}%;height:${l.rect.h*100}%"><span>${i+1} ↗</span></a>`:'').join('');}
 function box(links){return links.length?`<div class="resource-box"><strong>روابط الشريحة</strong><div class="resource-items">${links.map((l,i)=>`<a class="resource-item" data-link-index="${i}" href="${escape(l.url)}" target="_blank" rel="noopener noreferrer"><span class="resource-label">${i+1}. ${escape(l.label)} ↗</span><span class="resource-address">${escape(l.url)}</span></a>`).join('')}</div></div>`:'';}
 function bind(root,penHandler){const items=[...root.querySelectorAll('[data-link-index]')];for(const item of items){const pair=items.filter(x=>x.dataset.linkIndex===item.dataset.linkIndex);const on=()=>pair.forEach(x=>x.classList.add('link-active'));const off=()=>{if(pair.includes(document.activeElement)||pair.some(x=>x.matches(':hover')))return;pair.forEach(x=>x.classList.remove('link-active'));};item.addEventListener('mouseenter',on);item.addEventListener('mouseleave',off);item.addEventListener('focus',on);item.addEventListener('blur',off);if(penHandler&&item.classList.contains('link-hotspot')){item.addEventListener('pointerdown',e=>{if(e.pointerType==='pen')penHandler(e);});item.addEventListener('click',e=>{if(e.pointerType==='pen')e.preventDefault();});}}}
 function render(root,surface,container,links,penHandler){surface.querySelector('.link-hotspots')?.remove();const layer=document.createElement('div');layer.className='link-hotspots';layer.innerHTML=areas(links);surface.append(layer);container.innerHTML=box(links);bind(root,penHandler);}
 window.LectureLinks={areas,box,bind,render};
})();
