'use strict';
(async()=>{
 const $=id=>document.getElementById(id),share=new URL(location.href).searchParams.get('section');
 const fail=text=>{$('pages').replaceChildren();$('pages').hidden=true;$('controls').hidden=true;$('sidebar').hidden=true;$('status').hidden=false;$('status').textContent=text;$('updated').textContent='';};
 if(!/^[a-f0-9]{48}$/.test(share||'')){fail('رابط الشعبة غير صحيح. استخدم الرابط الذي أرسله المدرس.');return;}
 try{
  const response=await fetch(window.LECTURE_PUBLISHING.apiBase+'/api/student/'+share,{cache:'no-store',credentials:'omit'});
  if(response.status===403){const gate=await response.clone().json();if(gate.error==='enrollment_required'&&gate.joinUrl?.startsWith(window.LECTURE_PUBLISHING.apiBase+'/learn/')){location.replace(gate.joinUrl);return;}}
  if(!response.ok){fail(response.status===404?'شرح هذه الشعبة غير متاح حاليًا. قد يكون المدرس أوقف مشاركته.':'تعذّر تحميل آخر نسخة. حاول تحديث الصفحة.');return;}
  const data=await response.json(),session=data.session,slides=data.slides||window.LECTURE_SLIDES;let index=Math.max(0,slides.findIndex(s=>s.id===new URL(location).searchParams.get('slideId')));if(!slides.length){fail('لا توجد شرائح متاحة في هذه الشعبة حاليًا.');return;}
  const sectionNav=document.getElementById('sectionNav');if(sectionNav){sectionNav.href='/learn/?enrollmentId='+encodeURIComponent(share);sectionNav.textContent='واجبات وصفحة الشعبة';}
  const addCovers=(target,id)=>{for(const c of session.covers?.[id]||[]){if(c.revealed)continue;const cover=document.createElement('div');cover.className='answer-cover';cover.textContent='الإجابة مغطاة';Object.assign(cover.style,{left:c.x*100+'%',top:c.y*100+'%',width:c.w*100+'%',height:c.h*100+'%'});target.append(cover);}};
  $('name').textContent=session.term+' / '+session.name;$('updated').textContent='آخر نشر: '+new Date(data.updatedAt).toLocaleString('ar-KW')+' · حدّث الصفحة للحصول على أحدث شرح.';
  const svgInk=(strokes,w,h)=>{const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.setAttribute('preserveAspectRatio','none');for(const s of strokes){if(s.kind==='text'){const g=document.createElementNS(ns,'g');g.innerHTML=window.LectureText.svg(s,w,h);svg.append(g);continue;}if(!['#6d28d9','#dc2626','#2563eb','#172033'].includes(s.color))continue;for(let i=0;i<s.points.length;i++){const a=s.points[Math.max(0,i-1)],b=s.points[i],p=document.createElementNS(ns,'path');p.setAttribute('d',`M${a.x*w} ${a.y*h} L${b.x*w+.001} ${b.y*h}`);p.setAttribute('fill','none');p.setAttribute('stroke',s.color);p.setAttribute('stroke-width',s.width*(.6+.4*(b.p||.5)));p.setAttribute('stroke-linecap','round');svg.append(p);}}return svg;};
  const pages=slides.map((slide,i)=>{const a=session.annotations[slide.id]||{slide:[],note:[]},page=document.createElement('section');page.className='page';const title=document.createElement('h2');title.textContent=`${i+1}. ${slide.title}`;const sheet=document.createElement('div');sheet.className='sheet'+(a.note.length?' with-notes':'');sheet.style.setProperty('--slide-ratio',slide.ratio);sheet.style.setProperty('--sheet-ratio',slide.ratio*(a.note.length?1.42:1));const surface=document.createElement('div');surface.className='slide';const img=document.createElement('img');img.loading=i===0?'eager':'lazy';img.src=slide.src;img.alt=slide.title;surface.append(img,svgInk(a.slide,slide.ratio*900,900));addCovers(surface,slide.id);sheet.append(surface);if(a.note.length){const note=document.createElement('div');note.className='note';note.append(svgInk(a.note,slide.ratio*900*.42,900));sheet.append(note);}const links=document.createElement('div');links.className='resources';page.append(title,sheet,links);window.LectureLinks.render(page,surface,links,slide.links||[]);for(const task of slide.assignments||[]){const link=document.createElement('a');link.className='assignment-link';link.textContent='واجب: '+task.title+' · '+task.maxGrade+' درجة'+(task.bonusMaxGrade?' + '+task.bonusMaxGrade+' بونص':'')+(task.canSubmit?'':' · التسليم مغلق');link.href='/learn/?enrollmentId='+encodeURIComponent(share)+'&assignmentId='+encodeURIComponent(task.id);page.append(link);}$('pages').append(page);return page;});
  const privateNotes=await window.LearnerNotes?.attach({slides,pages,enrollmentId:share});
  const thumbs=slides.map((slide,i)=>{const button=document.createElement('button');button.type='button';button.className='thumbnail';button.setAttribute('aria-label',`${i+1}. ${slide.title}`);const img=document.createElement('img');img.loading=i===0?'eager':'lazy';img.src=slide.src;img.alt='';const label=document.createElement('span');label.textContent=`${i+1}. ${slide.title}`;const preview=document.createElement('div');preview.className='thumb-preview';preview.append(img);addCovers(preview,slide.id);button.append(preview,label);button.onclick=()=>{index=i;show();};$('slide-list').append(button);return button;});
  const chapterSelect=$('chapterSelect'),chapters=[...new Set(slides.map(s=>String(s.chapter||'')))].filter(Boolean).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
  const chapterNames={'1':'الفصل الأول','2':'الفصل الثاني','3':'الفصل الثالث'};
  for(const chapter of chapters){const option=document.createElement('option');option.value=chapter;option.textContent=chapterNames[chapter]||'الفصل '+chapter;chapterSelect.append(option);}
  let chapter=new URL(location).searchParams.get('chapter')||'all';if(!chapters.includes(chapter))chapter='all';
  // An explicit slide link takes precedence over an incompatible saved chapter.
  if(chapter!=='all'&&new URL(location).searchParams.has('slideId')&&String(slides[index].chapter)!==chapter)chapter='all';
  chapterSelect.value=chapter;
  const selected=()=>slides.map((s,i)=>i).filter(i=>chapter==='all'||String(slides[i].chapter)===chapter);
  const show=()=>{const indices=selected();if(!indices.includes(index))index=indices[0];const position=indices.indexOf(index),u=new URL(location);u.searchParams.set('slideId',slides[index].id);if(chapter==='all')u.searchParams.delete('chapter');else u.searchParams.set('chapter',chapter);history.replaceState(null,'',u);pages.forEach((p,i)=>{p.hidden=i!==index;p.classList.toggle('chapter-excluded',!indices.includes(i));p.classList.toggle('chapter-last',i===indices.at(-1));});thumbs.forEach((b,i)=>{b.hidden=!indices.includes(i);if(i===index)b.setAttribute('aria-current','true');else b.removeAttribute('aria-current');});privateNotes?.show(index);$('counter').textContent=`${position+1} / ${indices.length}`;$('prev').disabled=position===0;$('next').disabled=position===indices.length-1;};
  chapterSelect.onchange=()=>{chapter=chapterSelect.value;show();};
  const navigate=step=>{const indices=selected(),position=indices.indexOf(index);index=indices[Math.max(0,Math.min(indices.length-1,position+step))];show();};
  $('prev').onclick=()=>navigate(-1);$('next').onclick=()=>navigate(1);$('toggle').onclick=()=>{document.body.classList.toggle('hide-ink');$('toggle').textContent=document.body.classList.contains('hide-ink')?'إظهار الملاحظات':'إخفاء الملاحظات';};$('print').onclick=async()=>{const button=$('print');button.disabled=true;try{await Promise.all(pages.filter(p=>!p.classList.contains('chapter-excluded')).flatMap(p=>[...p.querySelectorAll('img')]).map(img=>{img.loading='eager';return img.decode();}));await privateNotes?.beforePrint();window.print();}catch{alert('تعذّر تحميل بعض الشرائح. حدّث الصفحة قبل الطباعة.');}finally{button.disabled=false;}};
  $('showLinks').onchange=e=>document.body.classList.toggle('links-hidden',!e.target.checked);
  document.addEventListener('keydown',e=>{if(e.target.isContentEditable||['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();$(e.key==='ArrowDown'?'next':'prev').click();}});
  show();$('status').hidden=true;$('pages').hidden=false;$('controls').hidden=false;$('sidebar').hidden=false;
  // Refresh visibility when the teacher releases a task in this section.
  const visibleIds=JSON.stringify(slides.map(s=>s.id));let refreshing=false;
  setInterval(async()=>{if(document.hidden||refreshing)return;refreshing=true;try{const fresh=await fetch(response.url,{cache:'no-store',credentials:'same-origin'});if(fresh.ok){const latest=await fresh.json();if(JSON.stringify(latest.slides?.map(s=>s.id))!==visibleIds&&!privateNotes?.dirty())location.reload();}else if([401,403,404].includes(fresh.status))location.reload();}catch{}finally{refreshing=false;}},10000);
  // Reload a restored tab as well, so browser history cannot silently show a revoked copy.
  window.addEventListener('pageshow',e=>{if(e.persisted)location.reload();});
 }catch{fail('تعذّر الاتصال. حدّث الصفحة عند عودة الإنترنت لعرض آخر نسخة نشرها المدرس.');}
})();
